# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Local

stages:
  - stage: Deploy
    displayName: 'Deploy Stage'
    jobs:
      - deployment: DeployJob
        displayName: 'Sequential Deployment'
        environment: 'FABRIC-DEV'
        strategy:
            runOnce:
                deploy:
                  steps:
                    - checkout: self
                    #- task: UsePythonVersion@0
                    #  inputs:
                    #    versionSpec: '3.11'
                    #  displayName: 'Use Python 3.11'

                    - script: |
                        cd $(Build.SourcesDirectory)
                        python -m pip install --upgrade pip
                        python -m pip install --upgrade pip
                        python -m pip install --user pipx #needed for installing poetry
                        python -m pip install --user --upgrade pipx
                        python -m pipx ensurepath
                        python -m pipx install poetry
                        python -m pipx upgrade poetry
                        python -m  pip install fabric-cicd
                        poetry config virtualenvs.in-project true
                      displayName: 'Install dependencies'