trigger:
- main

pool: Local

stages:
  - stage: Deploy
    displayName: 'Deploy Stage'
    jobs:
      - deployment: DeployJob
        displayName: 'Sequential Deployment'
        environment: 'FABRIC-DEV'
        strategy:
            runOnce:
                deploy:
                  steps:
                    - checkout: self
                    #- task: UsePythonVersion@0
                    #  inputs:
                    #    versionSpec: '3.11'
                    #  displayName: 'Use Python 3.11'

                    - script: |
                        cd $(Build.SourcesDirectory)
                        python -m pip install build
                        python -m pip install requests
                        python -m pip install azure-identity
                        rm -rf ./dist # Clean previous builds
                        python -m build
                        cd ./dist
                        WHEEL_FILE=$(find "$(pwd)" -name "*.whl" -print -quit)                    
                        echo "##vso[task.setvariable variable=WHEEL_FILE]$WHEEL_FILE"
                        echo "Wheel file path: $WHEEL_FILE"
                    - task: PythonScript@0
                      inputs:
                        scriptSource: 'filePath'
                        scriptPath: '$(Build.SourcesDirectory)/devops_pipelines/deploy_wheels_file_to_fabric.py'
                      env:
                        FABRIC_TENANT_ID: $(FABRIC_TENANT_ID)
                        FABRIC_CLIENT_ID: $(FABRIC_CLIENT_ID)
                        FABRIC_CLIENT_SECRET: $(FABRIC_CLIENT_SECRET)
                        FABRIC_ENVIRONMENT_ID: $(FABRIC_ENVIRONMENT_ID)
                        FABRIC_WORKSPACE_ID: $(FABRIC_WORKSPACE_ID)
                        FABRIC_FILE_PATH: $(WHEEL_FILE)
                        PYTHONUNBUFFERED: '1'